import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
async function module(path) { const code = ts.transpileModule(fs.readFileSync(new URL(path, import.meta.url), 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText; return import('data:text/javascript;base64,' + Buffer.from(code).toString('base64')); }
const { tagMatches, filterCollection, sortTags, restoreTagFilters, appearanceSection, tagSwatch } = await module('../src/lib/prompt-studio/tag-presentation.ts');
const { randomizeMix, restoreMixChoices, uniqueMixOptions } = await module('../src/lib/prompt-studio/mixer-model.ts');
const option = (tag, weight = 1, locked = false) => ({ id: tag, tag, family: 'style', name: tag, weight, locked });
test('canonical underscores, aliases and separated search terms find the same tag', () => { const row = { tag: 'long_red_hair', name: 'Long hair', aliases: ['Scarlet'] }; assert.ok(tagMatches(row, 'red long')); assert.ok(tagMatches(row, 'scarlet hair')); assert.ok(tagMatches(row, 'long_red')); assert.ok(!tagMatches(row, 'blue')); });
test('artist-only and stale category filters cannot empty a character collection', () => { const rows = [{ tag: '1girl', name: 'Girl', group: 'subject' }]; assert.equal(filterCollection(rows, { query: '', group: 'artist', set: 3, page: 0 }, false).length, 1); assert.equal(filterCollection(rows, { query: '', group: '', set: 3, page: 0 }, true).length, 0); });
test('sorting never changes source data and invalid persisted filters recover', () => { const rows = [{ tag: 'z', name: 'Z' }, { tag: 'a', name: 'A' }]; assert.equal(sortTags(rows, 'tag')[0].tag, 'a'); assert.equal(rows[0].tag, 'z'); assert.equal(sortTags(rows, 'source'), rows); assert.deepEqual(restoreTagFilters({ query: 123, group: null, page: -1, set: NaN }), { query: '', group: '', page: 0, set: -1 }); });
test('appearance filters cover starter and database group IDs without invented previews', () => { assert.equal(appearanceSection('starter:hair_length'), 'hair'); assert.equal(appearanceSection('collection:characters:eye_color'), 'face'); assert.equal(appearanceSection('features'), 'fantasy'); assert.equal(tagSwatch('blue_hair', 'hair_color'), '#648bc6'); assert.equal(tagSwatch('blue_sky', 'background'), undefined); });
test('random terms preserve slot weights, locks, order and input data', () => { const choices = [option('a', .65), option('b', 1.4, true), option('c', 1.25)]; const pool = ['x','y','z','b','x'].map(tag => option(tag)); const before = JSON.stringify({ choices, pool }); const next = randomizeMix(choices, pool, 3, () => .25); assert.equal(next[1], choices[1]); assert.deepEqual(next.map(row => row.weight), [.65, 1.4, 1.25]); assert.equal(new Set(next.map(row => row.tag)).size, 3); assert.equal(JSON.stringify({ choices, pool }), before); });
test('random size protects locked terms and rejects insufficient or invalid pools', () => { const choices = [option('a', .7), option('b', 1.5, true), option('c', .9, true)]; assert.equal(randomizeMix(choices, [option('x')], 2.5), choices); assert.equal(randomizeMix(choices, [], 3), choices); const next = randomizeMix(choices, [], 2); assert.deepEqual(next.map(row => row.tag), ['b','c']); });
test('persisted mixtures reject malformed values, repair IDs and deduplicate tags', () => { const next = restoreMixChoices([null, option('a', .5, true), { ...option('b', 5), id: 'a' }, option(' a ', 1), { ...option('bad'), weight: NaN }]); assert.equal(next.length, 2); assert.equal(next[1].weight, 2); assert.equal(new Set(next.map(row => row.id)).size, 2); assert.equal(uniqueMixOptions([option('a'), option('a'), option(' ')]).length, 1); });
