"""Constants for the Anima Artist Mixer nodes."""

FUSION_INTERPOLATE = "interpolate"
FUSION_CONCAT_WITH_BASE = "concat_with_base"
FUSION_BASE_PRESERVE = "base_preserve"

ALIGN_BASE_ANCHORED = "base_anchored"
ALIGN_SHARED_BASE_IDS = "shared_base_ids"

COMBINE_CONCAT = "concat"
COMBINE_OUTPUT_AVG = "output_avg"
COMBINE_LOWRANK_AVG = "lowrank_avg"

MAX_ARTISTS = 32

STATIC_CAPTURE_K_DEFAULT = 6
STATIC_CAPTURE_K_MAX = 12

ANCHOR_SEEDS_POOL = [42, 100, 200, 300]  # Legacy fallback for old option payloads.
ANCHOR_SEEDS_MAX = len(ANCHOR_SEEDS_POOL)
ANCHOR_SEED_MAX = 0xffffffffffffffff
ANCHOR_LAYER_THRESHOLD_DISABLED = -1

ANCHOR_REFRESH_ONCE = "once"
ANCHOR_REFRESH_WARM_CACHE = "warm_cache"
ANCHOR_REFRESH_MODES = (
    ANCHOR_REFRESH_ONCE,
    ANCHOR_REFRESH_WARM_CACHE,
)
ANCHOR_KEYFRAME_UNIFORM_SIGMA = "uniform_sigma"
ANCHOR_KEYFRAME_ADAPTIVE_Q = "adaptive_q"
ANCHOR_KEYFRAME_MODES = (
    ANCHOR_KEYFRAME_UNIFORM_SIGMA,
    ANCHOR_KEYFRAME_ADAPTIVE_Q,
)
ANCHOR_CACHE_POINTS_DEFAULT = 8
ANCHOR_CACHE_POINTS_MIN = 2
ANCHOR_CACHE_POINTS_MAX = 12

WEIGHT_MIN = 0.0
WEIGHT_MAX = 4.0
